# Generated by Django 3.1.7 on 2021-03-30 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0002_auto_20210329_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='student_address',
            field=models.CharField(default='no address', max_length=40),
        ),
    ]
