# Generated by Django 3.1.7 on 2021-04-05 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_profile', '0003_students_student_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='local_guardian_address',
            field=models.CharField(default='no address', max_length=40),
        ),
        migrations.AddField(
            model_name='students',
            name='local_guardian_name',
            field=models.CharField(default='no address', max_length=40),
        ),
        migrations.AddField(
            model_name='students',
            name='local_guardian_phone',
            field=models.CharField(default='no address', max_length=40),
        ),
    ]
